# Generated by Django 4.0.2 on 2022-02-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='useraccount',
            name='area',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='block_no',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='district',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='house_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='mobilePhone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='road_no',
            field=models.CharField(default='', max_length=255),
        ),
    ]
