# Generated by Django 4.0.2 on 2022-03-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofileinfo_remove_useraccount_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'ordering': ['user_id']},
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
