# Generated by Django 4.0.2 on 2022-03-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
