# Generated by Django 4.0.2 on 2022-03-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_profile_pic_updated',
            field=models.BooleanField(default=False),
        ),
    ]
