# Generated by Django 4.0.2 on 2022-03-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('name', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
