# Generated by Django 4.0.2 on 2022-03-04 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 4, 21, 26, 20, 753399)),
            preserve_default=False,
        ),
    ]
