# Generated by Django 4.0.2 on 2022-03-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0002_contactus_createdtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=-1)),
                ('itemID', models.IntegerField(default=-1)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('timeStampUpdated', models.DateTimeField(auto_now=True)),
                ('timeStampCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='No name', max_length=100)),
                ('lastName', models.CharField(default='No name', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('phNo', models.IntegerField(default=-1, null=True)),
                ('qualifications', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=300)),
                ('status', models.CharField(default='', max_length=100)),
                ('timeStampUpdated', models.DateTimeField(auto_now=True)),
                ('timeStampCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopID', models.IntegerField(default=-1)),
                ('itemName', models.CharField(default='No name', max_length=100)),
                ('cost', models.FloatField(default=0, max_length=10)),
                ('accumulatedRating', models.FloatField(default=0, max_length=10)),
                ('itemImg', models.CharField(default='No name', max_length=100)),
                ('itemDetail', models.CharField(default='', max_length=300)),
                ('timeStampUpdated', models.DateTimeField(auto_now=True)),
                ('timeStampCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['itemName'],
            },
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=-1)),
                ('itemID', models.IntegerField(default=-1)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=300)),
                ('timeStampUpdated', models.DateTimeField(auto_now=True)),
                ('timeStampCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['comment'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=-1)),
                ('cartID', models.IntegerField(default=-1)),
                ('deliveryboyID', models.IntegerField(default=-1)),
                ('deliveryCost', models.FloatField(default=0, max_length=10)),
                ('totalCost', models.FloatField(default=0, max_length=10)),
                ('remark', models.CharField(default='', max_length=300)),
                ('dropLocation', models.CharField(default='', max_length=300)),
                ('orderTime', models.CharField(default='', max_length=100)),
                ('deliveryStatus', models.CharField(default='', max_length=100)),
                ('timeStampUpdated', models.DateTimeField(auto_now=True)),
                ('timeStampCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orderTime'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=-1)),
                ('orderID', models.IntegerField(default=-1)),
                ('timeStampUpdated', models.DateTimeField(auto_now=True)),
                ('timeStampCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orderID'],
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=-1)),
                ('shopName', models.CharField(default='No name', max_length=100)),
                ('review', models.FloatField(default=0, max_length=10, null=True)),
                ('isBanned', models.BooleanField()),
                ('detailedAddr', models.CharField(default='', max_length=300)),
                ('timeStampUpdated', models.DateTimeField(auto_now=True)),
                ('timeStampCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['shopName'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['user_id']},
        ),
    ]
