# Generated by Django 4.0.2 on 2022-03-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0003_cart_deliveryboy_item_itemreview_order_orderhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemImg',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
