# Generated by Django 4.0.2 on 2022-03-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0004_alter_item_itemimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='offerBDT',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='offerPercentage',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
