# Generated by Django 4.0.2 on 2022-03-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0005_shopinfo_offerbdt_shopinfo_offerpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='offerTill',
            field=models.DateField(null=True),
        ),
    ]
