# Generated by Django 4.0.2 on 2022-03-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0006_shopinfo_offertill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemreview',
            options={'ordering': ['timeStampUpdated']},
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='offerTill',
            field=models.DateField(blank=True, null=True),
        ),
    ]
