# Generated by Django 4.0.2 on 2022-03-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0007_alter_itemreview_options_alter_shopinfo_isbanned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='shopName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
