# Generated by Django 4.0.2 on 2022-04-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0009_alter_shopinfo_offerbdt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
