# Generated by Django 4.0.2 on 2022-04-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0012_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['timeStampCreated']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cartID',
            new_name='itemID',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
