# Generated by Django 4.0.2 on 2022-04-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0013_alter_order_options_rename_cartid_order_itemid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveryCost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveryStatus',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveryboyID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dropLocation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderTime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='remark',
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryStatusDeliveryboy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryStatusUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryStatusWorker',
            field=models.BooleanField(default=False),
        ),
    ]
