# Generated by Django 4.0.2 on 2022-04-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0014_remove_order_deliverycost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-timeStampUpdated']},
        ),
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'ordering': ['offerTill']},
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='shopName',
            field=models.CharField(default='New', max_length=100),
        ),
    ]
