# Generated by Django 4.0.2 on 2022-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0015_alter_order_options_alter_shopinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='detailedAddr',
            field=models.CharField(default='No Address', max_length=300),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='offerTill',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
    ]
