# Generated by Django 4.0.2 on 2022-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhorKuno', '0016_alter_shopinfo_detailedaddr_alter_shopinfo_offertill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemDetail',
            field=models.CharField(default='', max_length=900),
        ),
    ]
